stages:
  - build
  - test
  - package

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test
  dependencies:
    - build-job

package-job:
  stage: package
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn package
  dependencies:
    - test-job
  artifacts:
    paths:
      - target/*.jar
