stages:
  - build
  - test
  - package

# ---------------------------
# Stage 1: Build
# ---------------------------
build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Building the project..."
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

# ---------------------------
# Stage 2: Test
# ---------------------------
test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Running tests..."
    - mvn test
  dependencies:
    - build-job
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 1 hour

# ---------------------------
# Stage 3: Package
# ---------------------------
package-job:
  stage: package
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Packaging the application..."
    - mvn package
  dependencies:
    - test-job
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
