stages:
  - build
  - test
  - deploy

# Use official Maven image with JDK 17
image: maven:3.9.6-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

# Stage 1: Build
build-job:
  stage: build
  script:
    - echo "installing dependencies ..."
    - mvn clean install
  artifacts:
    paths:
      - target/
  only:
    - main

# Stage 2: Test
test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
  only:
    - main

# Stage 3: Deploy (dummy step)
deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Hello app deployed successfully!"
  only:
    - main

